version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "monthly"
    # Group Dependabot updates into one single PR.
    groups:
      dependencies:
        patterns:
          - "*"
